# Generated by Django 4.1.2 on 2022-11-02 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horas_trabajados',
            new_name='Horas_trabajadas',
        ),
        migrations.RenameField(
            model_name='horas_trabajadas',
            old_name='hora_trabajado',
            new_name='hora_trabajada',
        ),
    ]
