# Generated by Django 4.1.2 on 2022-11-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0002_alter_horas_trabajadas_dia_actual_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='banner',
            field=models.ImageField(blank=True, default='APPCanal1/static/assets/img/banner.png', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(blank=True, default='APPCanal1/static/assets/img/usuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
    ]
