# Generated by Django 4.1.2 on 2022-11-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0003_alter_perfil_banner_alter_perfil_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
