# Generated by Django 4.1.2 on 2022-11-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0004_delete_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='image',
        ),
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='avatares/usuario.png', null=True, upload_to='avatares'),
        ),
    ]
