# Generated by Django 4.1.2 on 2022-11-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0005_remove_avatar_image_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcc',
            name='avatar',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/media/avatares/usuario.png', null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='personaldxtv',
            name='avatar',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/media/avatares/usuario.png', null=True, upload_to='avatares'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='avatar',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/media/avatares/usuario.png', null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/media/avatares/usuario.png', null=True, upload_to='avatares'),
        ),
    ]
