# Generated by Django 4.1.2 on 2022-11-15 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('APPCanal1', '0006_personalcc_avatar_personaldxtv_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcc',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='personaldxtv',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/media/avatares/usuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=''),
        ),
    ]
