# Generated by Django 4.1.2 on 2022-11-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0007_remove_personalcc_avatar_remove_personaldxtv_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='usuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
    ]
