# Generated by Django 4.1.2 on 2022-11-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0009_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcc',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatares/usuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='personaldxtv',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatares/usuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='usuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
    ]
