# Generated by Django 4.1.2 on 2022-11-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0010_personalcc_avatar_personaldxtv_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalcc',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='personaldxtv',
            name='avatar',
        ),
        migrations.AddField(
            model_name='personalcc',
            name='avatar',
            field=models.ManyToManyField(related_name='PersonalCC_Avatar', to='APPCanal1.avatar'),
        ),
        migrations.AddField(
            model_name='personaldxtv',
            name='avatar',
            field=models.ManyToManyField(related_name='PersonalDXTV_Avatar', to='APPCanal1.avatar'),
        ),
    ]
