# Generated by Django 4.1.2 on 2022-11-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0015_alter_personalcc_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcc',
            name='avatar',
            field=models.ImageField(blank=True, default='APPCanal1/static/asset/img/susuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
    ]
