# Generated by Django 4.1.2 on 2022-11-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0016_alter_personalcc_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcc',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatares/usuario.png', null=True, upload_to='avatares', verbose_name='Avatar'),
        ),
    ]
