# Generated by Django 4.1.2 on 2022-11-15 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APPCanal1', '0020_remove_perfil_avatar_perfil_imagen_alter_avatar_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
